# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-05-04 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hack', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='time',
            field=models.DateTimeField(null=True),
        ),
    ]
